services:
  postgres:
    image: postgres:16
    container_name: proyecto_libreria_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: proyecto_libreria
      POSTGRES_USER: libreria_user
      POSTGRES_PASSWORD: libreria_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
